training.set=./dataset/iFashion_UB/train.txt
test.set=./dataset/iFashion_UB/test.txt
dataset.name=iFashion_UB
model.name=BOD
model.type=graph
seed=3407
item.ranking=-topN 10,20
embbedding.size=64
num.max.epoch=30
batch_size=256
learnRate=0.001
reg.lambda=0.0001
trainmodel=LightGCN
generator=VAE
weight.mode=per_sample
LightGCN=-n_layer 1
GM_AU=-generator_lr 0.0005 -generator_reg 0.0001 -generator_emb_size 64 -outer_loop 1 -inner_loop 1 -outer_batch_size 128 -weight_bpr 1 -weight_alignment 1 -weight_uniformity 0.35
output.setup=-dir ./results/
